// Mocks generated by Mockito 5.4.4 from annotations
// in test_case/test/features/chat/chat_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_case/features/chat/model/chat_message_model.dart' as _i4;
import 'package:test_case/features/chat/repository/chat_room_repository.dart'
    as _i2;
import 'package:test_case/features/home/models/chat_room_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IChatRoomRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChatRoomRepository extends _i1.Mock
    implements _i2.IChatRoomRepository {
  MockIChatRoomRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.ChatMessage>> getMessages(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [roomId],
        ),
        returnValue: _i3.Stream<List<_i4.ChatMessage>>.empty(),
      ) as _i3.Stream<List<_i4.ChatMessage>>);

  @override
  _i3.Future<void> sendMessage(_i4.ChatMessage? message) => (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markAsRead(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [messageId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<List<_i5.ChatRoom>> getChatRooms(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatRooms,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i5.ChatRoom>>.empty(),
      ) as _i3.Stream<List<_i5.ChatRoom>>);
}
